workflows:
  android-workflow:
    name: Android APK (Capacitor)
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      vars:
        NODE_VERSION: 18
      node: 18

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Next.js (static export)
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
